### ISSUE TITLE
lessThan returns false when it should return true, mediaType returns a larger value than it should

### ISSUE THREAD

**Issue by kb8228** [AlecAivazis/redux-responsive#106] opened 2018-07-10 19:06 UTC
This library now works the opposite of what it used to. At user-defined desktop breakpoint of 800px:

- and screen width of 799px:
1. mediaType is 'desktop' (next breakpoint of 800px)
2. lessThan 'desktop' returns false, when it should return true
3. is 'desktop' returns true, when it should return false

- and screen width of 801px:
1. mediaType is 'large' (next breakpoint of 1024px)
2. lessThan 'large' returns false, when it should return true
3. is 'large' returns true, when it should return false

**Comment by AlecAivazis** [comment] 2018-07-12 15:22
hey @kb8228 - thanks for reporting this. This definitely sounds like a regression, just to be clear is `mediaType` right but `is` and `lessThan` wrong?

**Comment by AlecAivazis** [comment] 2018-07-12 18:44
So first let me apologize, i wasn't reading closely enough when I first replied. That being said, i'm slightly confused - it sounds like what you are describing is intended. The various breakpoints are (and have always been) the upper bounds of the ranges for each label. This is the reason we allow users to customize the `infinity` type and not something like the `zero` type. 

Taking the example from the README, if these are the defined breakpoints: 
```
{
        extraSmall: 500,
        small: 700,
        medium: 1000,
        large: 1280,
        extraLarge: 1400,
    }
```

with a browser width at 499, the `mediaType` should be `extraSmall`. At `501`, it should be `small`.

**Comment by kb8228** [comment] 2018-07-12 19:08
It seems like this util used to work differently. As of recent, the codebase I'm working in has unexpected breakpoints where the util is required.

**Comment by AlecAivazis** [comment] 2018-07-12 19:10
Huh - how long ago was the behavior you expected exhibited? The api hasn't changed in awhile.

**Comment by AlecAivazis** [comment] 2018-07-12 20:15
Hm so the latest update that impacted anything was 3 months ago when we updated the library to take advantage of changes in redux 4.  The other recent changes were all associated with the typescript type declarations, I'm not sure what could be impacting the change in behavior. Did you maybe update to a new major version?

**Comment by AlecAivazis** [comment] 2018-07-14 16:13
I'm going to close this since I don't think its actually a bug, i'm sorry for any confusion you encountered.

**Closed by AlecAivazis** 2018-07-14 16:13 UTC
