### ISSUE TITLE
Any example integrated with ImmutableJS?

### ISSUE THREAD

**Issue by raymondsze** [AlecAivazis/redux-responsive#37] opened 2016-07-26 05:45 UTC
as title, I would like to save the state to Immutable Store, so the reducer have to be Immutable Reducer.

**Comment by AlecAivazis** [comment] 2016-07-26 08:35
Hmm maybe I'm a bit confused here but I'm pretty sure this library will integrate seamlessly with your reducers that written with immutable js.

**Comment by kandros** [comment] 2016-07-26 14:06
using https://github.com/gajus/redux-immutable without problems

**Comment by AlecAivazis** [comment] 2016-07-26 15:35
Thanks for the input @kandros - I'm going to close this @raymondsze, please feel free to say something if you're still running into issues and I'll happily reopen this ticket

**Closed by AlecAivazis** 2016-07-26 15:35 UTC

**Comment by shanecav** [comment] 2016-11-08 21:06
Looks like usage with `redux-immutable` doesn't work with performance mode. I believe the issue is at https://github.com/AlecAivazis/redux-responsive/blob/master/src/util/addPerformanceModeHandlers.js#L20-L32, due to the use of `Object.keys` to search for the `responsiveReducer`. `Object.keys` won't return anything useful if your root state is an Immutable type.

One possible fix would be to change how `responsiveReducer` is found by first checking if `storeState` is an Immutable type (e.g. by `typeof storeState.toJS === 'function'` or something like that).

If it is an Immutable, then you could search for the `responsiveReducer` with:

```
responsiveReducer = storeState.find((val) => val._responsiveState)
```

If it's not an Immutable, then it would search with the current `Object.keys` approach.

@AlecAivazis if that solution looks good, I can put together a PR for it.

**Comment by AlecAivazis** [comment] 2016-11-08 21:45
Ah good point @shanecav - that definitely would work to get around the problem. I'd love to review a PR with the changes if you have the time. Part of me feels like the way I'm looking for the reducer is a bit flawed. Can you think of a better way to get access to the reducer's current value without knowing its name before hand?

**Comment by shanecav** [comment] 2016-11-09 00:49
Hmm... Good question. I can't think of a way around searching for it unless you require the user to explicitly set the `redux-responsive` branch of state key + reducer function in the `createResponsiveStoreEnhancer` config, which would change the user's setup process quite a bit.

I'll put together a PR with my previous solution when I get a minute, to at least fix `redux-immutable` + performance mode compatibility for the time being.
