### ISSUE TITLE
Make react-redux non-mandatory

### ISSUE THREAD

**Issue by ValeriiVasin** [AlecAivazis/redux-responsive#30] opened 2016-07-08 16:16 UTC
We are using redux with Angular2. And current version of the redux-responsive project is not allowing to use it in non-react environment. Because of StyleSheet component that is relying on `react-redux`.

Probably it could be related to another issue: https://github.com/AlecAivazis/redux-responsive/issues/16 for bringing more modular build.

**Comment by AlecAivazis** [comment] 2016-07-08 17:40
Hey @ValeriiVasin - thanks for trying out my package. I'm sorry you ran into some problems. I'm a bit confused however. React *is* in fact a depdency to use the react components, but as I mentioned in that issue thread, none of the react-related packages are included in the bundled code (see [here](https://github.com/AlecAivazis/redux-responsive/blob/master/config/webpack.js#L60)), nor are they even listed as explicit depdencies in the project's [package.json](https://github.com/AlecAivazis/redux-responsive/blob/master/package.json). Npm shouldn't be downloading react/react-redux because of this package.

**Comment by ValeriiVasin** [comment] 2016-07-11 09:50
@AlecAivazis thx for quick response. 
In fact, i was thinking that `redux-responsive` is nothing more (or started with that in a mind) then just enhancer + reducer that will bring screen size into the store (as it showed in examples). And with that in a mind - i would assume that it is framework agnostic, like redux is.

Most of devs are now using build tools. In our case it is webpack. In order to build our project after adding `redux-responsive` - it is required to have react/react-redux installed by npm. Otherwise you will get an error:
```
ERROR in ./~/redux-responsive/build/index.js
Module not found: Error: Cannot resolve module 'react-redux' in ./node_modules/redux-responsive/build
 @ ./~/redux-responsive/build/index.js 1:30238-30260
```

Moreover I would assume that Angular2 (or some other framework) users would be happy, if  `redux-responsive` will not provide some react-related components (e.g. StyleSheet) which they do not need. React components could be extracted into `react-redux-responsive` or smth :)

What do you think about that? Is it somehow similar to redux-responsive project development directions or it is going to be coupled with react?

**Comment by AlecAivazis** [comment] 2016-07-11 15:41
Huh, that's definitely a problem - thanks for sharing this! I might be able to fix it with some import re-organization but if not, i'll make a separate package like you suggest.

**Comment by AlecAivazis** [comment] 2016-07-12 05:11
@ValeriiVasin I think I have a fix implemented [], could you try adding the specific commit as a dependency so I can test before publishing:
```
...
     'redux-responsive': 'git://github.com/AlecAIvazis/redux-responsive.git#b4fc05f'
...
```

**Comment by ValeriiVasin** [comment] 2016-07-12 09:59
@AlecAivazis It is working in some kind. 

1) its not possible to test it from git commit (like it your example) - because there are no build files (devDeps will not be installed for dependent package)
2) I managed to make it work using `npm link` from the branch `new build` that you provided, But there is some issue as well. You changed main file of npm to index.js, but actual file that is generated by webpack - `6f9d4f293caae374c86a.js`.

Otherwise everything works fine :) at least for our project.

**Comment by AlecAivazis** [comment] 2016-07-12 15:44
Hmmm i can't seem to reproduce 2. When I try to run `gulp build:prod` in my local project I get two different files generated: `index.js` and `react.js`. Could you try doing the same? Sorry this is so challenge - still wrapping my head around the best way to structure an npm package once they get larger than a single export.

**Comment by ValeriiVasin** [comment] 2016-07-12 17:01
@AlecAivazis if it works for you - then fine :) you are the one who is releasing at the end :)

I have no idea why its behaving like that and probably its not really related to the current issue. We are using webpack directly in all our projects, that is why its a bit tricky to debug gulp-releated stuff that is doing webpack at the end. Hope screenshot will help somehow :)

BTW, eslint is also failing for me - that is why I turned it off. It could be related that i am having another .eslintrc.json in the home directory (that could probably be outdated).

![screenshot](http://i.imgur.com/7DPINY4.gif)

**Comment by AlecAivazis** [comment] 2016-07-13 04:32
Oh sorry, i just published it as a beta version so if you could add `redux-responsive@beta` as a dependency, I'd like to verify that your problem is fixed before I publish this for everyone else

**Comment by ValeriiVasin** [comment] 2016-07-14 19:57
@AlecAivazis Sorry for the delay. Checked it right now: @beta works fine for our project :)

**Comment by AlecAivazis** [comment] 2016-07-16 17:21
@ValeriiVasin i'm going to close this since I published the fix. Please let me know if you run into any more problems using angular.

**Closed by AlecAivazis** 2016-07-16 17:21 UTC
